"""empty message

Revision ID: 13975a13720f
Revises: ff1a89ef8c8c
Create Date: 2017-08-02 00:07:02.203571

"""

# revision identifiers, used by Alembic.
revision = '13975a13720f'
down_revision = 'ff1a89ef8c8c'

from alembic import op
import sqlalchemy as sa
import citext


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('series', sa.Column('rating', sa.Float(), nullable=True))
    op.add_column('serieschanges', sa.Column('rating', sa.Float(), nullable=True))
    op.create_check_constraint('ck_aggregate_rating_value', 'series', '(rating >= 0 and rating <= 10) or rating IS NULL')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('serieschanges', 'rating')
    op.drop_column('series', 'rating')
    ### end Alembic commands ###
