"""empty message

Revision ID: 16460f9e4e3
Revises: 31b6ae3f13f
Create Date: 2015-10-16 18:33:59.540693

"""

# revision identifiers, used by Alembic.
revision = '16460f9e4e3'
down_revision = '31b6ae3f13f'

from alembic import op
import sqlalchemy as sa
import citext


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ratings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('series_id', sa.Integer(), nullable=True),
    sa.Column('source_ip', sa.Text(), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.CheckConstraint('(user_id IS NOT NULL AND source_ip IS NULL) OR (user_id IS NULL AND source_ip IS NOT NULL)', name='rating_src'),
    sa.CheckConstraint('rating <= 10', name='rating_max'),
    sa.CheckConstraint('rating >=  0', name='rating_min'),
    sa.ForeignKeyConstraint(['series_id'], ['series.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id'),
    sa.UniqueConstraint('user_id', 'source_ip')
    )
    op.create_index(op.f('ix_ratings_user_id'), 'ratings', ['user_id'], unique=False)
    op.create_index(op.f('ix_ratings_series_id'), 'ratings', ['series_id'], unique=False)
    op.create_index(op.f('ix_ratings_source_ip'), 'ratings', ['source_ip'], unique=False)

    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ratings')
    ### end Alembic commands ###
