"""empty message

Revision ID: 1fa3d1e34
Revises: 16460f9e4e3
Create Date: 2015-10-18 18:24:39.078333

"""

# revision identifiers, used by Alembic.
revision = '1fa3d1e34'
down_revision = '16460f9e4e3'

from alembic import op
import sqlalchemy as sa
import citext


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_ratings_series_id'), 'ratings', ['series_id'], unique=False)
    op.create_index(op.f('ix_ratings_source_ip'), 'ratings', ['source_ip'], unique=False)
    op.create_index(op.f('ix_ratings_user_id'), 'ratings', ['user_id'], unique=False)
    op.drop_constraint('ratings_user_id_key', 'ratings', type_='unique')
    op.drop_constraint('ratings_user_id_source_ip_key', 'ratings', type_='unique')
    op.create_unique_constraint(None, 'ratings', ['user_id', 'series_id'])
    op.create_unique_constraint(None, 'ratings', ['source_ip', 'series_id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ratings', type_='unique')
    op.drop_constraint(None, 'ratings', type_='unique')
    op.create_unique_constraint('ratings_user_id_source_ip_key', 'ratings', ['user_id', 'source_ip'])
    op.create_unique_constraint('ratings_user_id_key', 'ratings', ['user_id'])
    op.drop_index(op.f('ix_ratings_user_id'), table_name='ratings')
    op.drop_index(op.f('ix_ratings_source_ip'), table_name='ratings')
    op.drop_index(op.f('ix_ratings_series_id'), table_name='ratings')




















    ### end Alembic commands ###
