"""empty message

Revision ID: 2eea308400d
Revises: None
Create Date: 2015-10-05 19:21:30.521604

"""

# revision identifiers, used by Alembic.
revision = '2eea308400d'
down_revision = None

from alembic import op
import sqlalchemy as sa
import citext


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('forum_boards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('slug', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('forum_roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('forum_threads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(length=80), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('board_id', sa.Integer(), nullable=True),
    sa.Column('length', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['board_id'], ['forum_boards.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_forum_threads_author_id'), 'forum_threads', ['author_id'], unique=False)
    op.create_index(op.f('ix_forum_threads_board_id'), 'forum_threads', ['board_id'], unique=False)
    op.create_table('user_role_assoc',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['forum_roles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'role_id')
    )
    op.create_table('forum_posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.Column('index', sa.Integer(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('thread_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['thread_id'], ['forum_threads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_forum_posts_author_id'), 'forum_posts', ['author_id'], unique=False)
    op.create_index(op.f('ix_forum_posts_index'), 'forum_posts', ['index'], unique=False)
    op.create_index(op.f('ix_forum_posts_thread_id'), 'forum_posts', ['thread_id'], unique=False)
    op.create_index(op.f('ix_news__posts_timestamp'), 'news__posts', ['timestamp'], unique=False)
    op.create_index(op.f('ix_releaseschanges_series'), 'releaseschanges', ['series'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_releaseschanges_series'), table_name='releaseschanges')
    op.drop_index(op.f('ix_news__posts_timestamp'), table_name='news__posts')
    op.drop_index(op.f('ix_forum_posts_thread_id'), table_name='forum_posts')
    op.drop_index(op.f('ix_forum_posts_index'), table_name='forum_posts')
    op.drop_index(op.f('ix_forum_posts_author_id'), table_name='forum_posts')
    op.drop_table('forum_posts')
    op.drop_table('user_role_assoc')
    op.drop_index(op.f('ix_forum_threads_board_id'), table_name='forum_threads')
    op.drop_index(op.f('ix_forum_threads_author_id'), table_name='forum_threads')
    op.drop_table('forum_threads')
    op.drop_table('forum_roles')
    op.drop_table('forum_boards')
    ### end Alembic commands ###
