"""empty message

Revision ID: 31b6ae3f13f
Revises: 78ebb55819
Create Date: 2015-10-08 19:59:30.500689

"""

# revision identifiers, used by Alembic.
revision = '31b6ae3f13f'
down_revision = '78ebb55819'

from alembic import op
import sqlalchemy as sa
import citext


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('series', sa.Column('pub_date', sa.DateTime(), nullable=True))
    op.add_column('serieschanges', sa.Column('pub_date', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('serieschanges', 'pub_date')
    op.drop_column('series', 'pub_date')
    ### end Alembic commands ###
