"""empty message

Revision ID: 355ab81681f
Revises: 434c1237574
Create Date: 2015-11-12 19:45:07.995579

"""

# revision identifiers, used by Alembic.
revision = '355ab81681f'
down_revision = '434c1237574'

from alembic import op
import sqlalchemy as sa
import citext


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wiki_page',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', citext.CIText(), nullable=True),
    sa.Column('slug', citext.CIText(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('changeuser', sa.Integer(), nullable=True),
    sa.Column('changetime', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['changeuser'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug'),
    sa.UniqueConstraint('title')
    )
    op.create_index(op.f('ix_wiki_page_changetime'), 'wiki_page', ['changetime'], unique=False)
    op.create_index(op.f('ix_wiki_page_changeuser'), 'wiki_page', ['changeuser'], unique=False)
    op.create_table('wiki_pagechanges',
    sa.Column('operation', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', citext.CIText(), nullable=True),
    sa.Column('slug', citext.CIText(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('srccol', sa.Integer(), nullable=True),
    sa.Column('changeuser', sa.Integer(), nullable=True),
    sa.Column('changetime', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['changeuser'], ['users.id'], ),
    sa.ForeignKeyConstraint(['srccol'], ['wiki_page.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wiki_pagechanges_changetime'), 'wiki_pagechanges', ['changetime'], unique=False)
    op.create_index(op.f('ix_wiki_pagechanges_changeuser'), 'wiki_pagechanges', ['changeuser'], unique=False)
    op.create_index(op.f('ix_wiki_pagechanges_srccol'), 'wiki_pagechanges', ['srccol'], unique=False)

    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###

    op.drop_index(op.f('ix_wiki_pagechanges_srccol'), table_name='wiki_pagechanges')
    op.drop_index(op.f('ix_wiki_pagechanges_changeuser'), table_name='wiki_pagechanges')
    op.drop_index(op.f('ix_wiki_pagechanges_changetime'), table_name='wiki_pagechanges')
    op.drop_table('wiki_pagechanges')
    op.drop_index(op.f('ix_wiki_page_changeuser'), table_name='wiki_page')
    op.drop_index(op.f('ix_wiki_page_changetime'), table_name='wiki_page')
    op.drop_table('wiki_page')
    ### end Alembic commands ###
