"""empty message

Revision ID: 434c1237574
Revises: 1fa3d1e34
Create Date: 2015-10-18 18:26:17.622389

"""

# revision identifiers, used by Alembic.
revision = '434c1237574'
down_revision = '1fa3d1e34'

from alembic import op
import sqlalchemy as sa
import citext


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ratings_source_ip_series_id_key', 'ratings', type_='unique')
    op.drop_constraint('ratings_user_id_series_id_key', 'ratings', type_='unique')
    op.create_unique_constraint(None, 'ratings', ['user_id', 'source_ip', 'series_id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ratings', type_='unique')
    op.create_unique_constraint('ratings_user_id_series_id_key', 'ratings', ['user_id', 'series_id'])
    op.create_unique_constraint('ratings_source_ip_series_id_key', 'ratings', ['source_ip', 'series_id'])
    ### end Alembic commands ###
