"""empty message

Revision ID: 4e7768822b3
Revises: None
Create Date: 2015-04-17 21:15:47.843242

"""

# revision identifiers, used by Alembic.
revision = '4e7768822b3'
down_revision = None

from alembic import op
import sqlalchemy as sa
import citext

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('series',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', citext.CIText(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('type', sa.Text(), nullable=True),
    sa.Column('origin_loc', sa.Text(), nullable=True),
    sa.Column('demographic', sa.Text(), nullable=True),
    sa.Column('orig_lang', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nickname', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('about_me', sa.String(length=140), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_nickname'), 'user', ['nickname'], unique=True)
    op.create_table('translators',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_name', sa.Text(), nullable=False),
    sa.Column('group_site', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('group_name')
    )
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    op.create_table('releases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('series', sa.Integer(), nullable=True),
    sa.Column('volume', sa.Float(), nullable=False),
    sa.Column('chapter', sa.Float(), nullable=False),
    sa.Column('tlgroup', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['series'], ['series.id'], ),
    sa.ForeignKeyConstraint(['tlgroup'], ['translators.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('series', sa.Integer(), nullable=True),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('tag', citext.CIText(), nullable=False),
    sa.ForeignKeyConstraint(['series'], ['series.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('series', 'tag')
    )
    op.create_index(op.f('ix_tags_tag'), 'tags', ['tag'], unique=False)
    op.create_table('author',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('series', sa.Integer(), nullable=True),
    sa.Column('author', citext.CIText(), nullable=False),
    sa.ForeignKeyConstraint(['series'], ['series.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('series', 'author')
    )
    op.create_index(op.f('ix_author_author'), 'author', ['author'], unique=False)
    op.create_table('covers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('srcfname', sa.Text(), nullable=True),
    sa.Column('series', sa.Integer(), nullable=True),
    sa.Column('volume', sa.Float(), nullable=True),
    sa.Column('chapter', sa.Float(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('fspath', sa.Text(), nullable=True),
    sa.Column('hash', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['series'], ['series.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('illustrators',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('series', sa.Integer(), nullable=True),
    sa.Column('name', citext.CIText(), nullable=False),
    sa.ForeignKeyConstraint(['series'], ['series.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('series', 'name')
    )
    op.create_index(op.f('ix_illustrators_name'), 'illustrators', ['name'], unique=False)
    op.create_table('post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('seriesTopic', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('genres',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('series', sa.Integer(), nullable=True),
    sa.Column('genre', citext.CIText(), nullable=False),
    sa.ForeignKeyConstraint(['series'], ['series.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('series', 'genre')
    )
    op.create_index(op.f('ix_genres_genre'), 'genres', ['genre'], unique=False)
    op.create_table('alternate_names',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('series', sa.Integer(), nullable=True),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('cleanname', citext.CIText(), nullable=False),
    sa.ForeignKeyConstraint(['series'], ['series.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alternate_names_cleanname'), 'alternate_names', ['cleanname'], unique=False)
    op.create_index(op.f('ix_alternate_names_name'), 'alternate_names', ['name'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_alternate_names_name'), table_name='alternate_names')
    op.drop_index(op.f('ix_alternate_names_cleanname'), table_name='alternate_names')
    op.drop_table('alternate_names')
    op.drop_index(op.f('ix_genres_genre'), table_name='genres')
    op.drop_table('genres')
    op.drop_table('post')
    op.drop_index(op.f('ix_illustrators_name'), table_name='illustrators')
    op.drop_table('illustrators')
    op.drop_table('covers')
    op.drop_index(op.f('ix_author_author'), table_name='author')
    op.drop_table('author')
    op.drop_index(op.f('ix_tags_tag'), table_name='tags')
    op.drop_table('tags')
    op.drop_table('releases')
    op.drop_table('followers')
    op.drop_table('translators')
    op.drop_index(op.f('ix_user_nickname'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_table('series')
    ### end Alembic commands ###
