"""empty message

Revision ID: 6e4c83c81d6f
Revises: 28d5f385d913
Create Date: 2017-08-02 22:17:08.820519

"""

# revision identifiers, used by Alembic.
revision = '6e4c83c81d6f'
down_revision = '28d5f385d913'

from alembic import op
import sqlalchemy as sa
import citext


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_alternatenames_series', table_name='alternatenames')
    op.drop_index('idx_series', table_name='alternatenames')
    op.drop_index('idx_author_series', table_name='author')
    op.drop_index('idx_covers_series', table_name='covers')
    op.drop_index('idx_genres_series', table_name='genres')
    op.drop_index('idx_illustrators_series', table_name='illustrators')
    op.drop_index('ix_posts_timestamp', table_name='news__posts')
    op.drop_index('idx_releases_series', table_name='releases')
    op.drop_index('idx_tags_series', table_name='tags')
    op.drop_index('idx_tagschanges_series', table_name='tagschanges')
    op.drop_index('idx_watches_series', table_name='watches')
    op.drop_index('idx_alternatenameschanges_series', table_name='alternatenameschanges')
    op.drop_index('idx_authorchanges_series', table_name='authorchanges')
    op.drop_index('idx_coverschanges_series', table_name='coverschanges')
    op.drop_index('idx_genreschanges_series', table_name='genreschanges')
    op.drop_index('idx_illustratorschanges_series', table_name='illustratorschanges')
    op.drop_index('idx_releaseschanges_series', table_name='releaseschanges')
    op.drop_index('idx_serieschanges_series', table_name='serieschanges')


    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_watches_series', 'watches', ['series_id'], unique=False)
    op.create_index('idx_tagschanges_series', 'tagschanges', ['series'], unique=False)
    op.create_index('idx_tags_series', 'tags', ['series'], unique=False)
    op.create_index('idx_serieschanges_series', 'serieschanges', ['srccol'], unique=False)
    op.create_index('idx_releaseschanges_series', 'releaseschanges', ['series'], unique=False)
    op.create_index('idx_releases_series', 'releases', ['series'], unique=False)
    op.create_index('ix_posts_timestamp', 'news__posts', ['timestamp'], unique=False)
    op.create_index('idx_illustratorschanges_series', 'illustratorschanges', ['series'], unique=False)
    op.create_index('idx_illustrators_series', 'illustrators', ['series'], unique=False)
    op.create_index('idx_genreschanges_series', 'genreschanges', ['series'], unique=False)
    op.create_index('idx_genres_series', 'genres', ['series'], unique=False)
    op.create_index('idx_coverschanges_series', 'coverschanges', ['series'], unique=False)
    op.create_index('idx_covers_series', 'covers', ['series'], unique=False)
    op.create_index('idx_authorchanges_series', 'authorchanges', ['series'], unique=False)
    op.create_index('idx_author_series', 'author', ['series'], unique=False)
    op.create_index('idx_alternatenameschanges_series', 'alternatenameschanges', ['series'], unique=False)
    op.create_index('idx_series', 'alternatenames', ['series'], unique=False)
    op.create_index('idx_alternatenames_series', 'alternatenames', ['series'], unique=False)
    ### end Alembic commands ###
