"""empty message

Revision ID: 75719b64908d
Revises: e5324ae0d804
Create Date: 2018-01-14 17:22:11.362680

"""

# revision identifiers, used by Alembic.
revision = '75719b64908d'
down_revision = 'e5324ae0d804'

from alembic import op
import sqlalchemy as sa
import citext


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'db_tags_link', ['series_id', 'tag_id'])
    op.add_column('series', sa.Column('release_count', sa.Integer(), nullable=True))
    op.add_column('serieschanges', sa.Column('release_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('serieschanges', 'release_count')
    op.drop_column('series', 'release_count')
    op.drop_constraint(None, 'db_tags_link', type_='unique')
    # ### end Alembic commands ###
