"""empty message

Revision ID: 78ebb55819
Revises: 28ccc9a34fd
Create Date: 2015-10-08 19:58:05.557569

"""

# revision identifiers, used by Alembic.
revision = '78ebb55819'
down_revision = '28ccc9a34fd'

from alembic import op
import sqlalchemy as sa
import citext


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('publishers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', citext.CIText(), nullable=False),
    sa.Column('site', sa.Text(), nullable=True),
    sa.Column('series', sa.Integer(), nullable=True),
    sa.Column('changetime', sa.DateTime(), nullable=False),
    sa.Column('changeuser', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['changeuser'], ['users.id'], ),
    sa.ForeignKeyConstraint(['series'], ['series.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('series', 'name')
    )
    op.create_index(op.f('ix_publishers_changetime'), 'publishers', ['changetime'], unique=False)
    op.create_index(op.f('ix_publishers_changeuser'), 'publishers', ['changeuser'], unique=False)
    op.create_table('publisherschanges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', citext.CIText(), nullable=False),
    sa.Column('site', sa.Text(), nullable=True),
    sa.Column('operation', sa.Text(), nullable=True),
    sa.Column('srccol', sa.Integer(), nullable=True),
    sa.Column('series', sa.Integer(), nullable=True),
    sa.Column('changetime', sa.DateTime(), nullable=False),
    sa.Column('changeuser', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['changeuser'], ['users.id'], ),
    sa.ForeignKeyConstraint(['series'], ['series.id'], ),
    sa.ForeignKeyConstraint(['srccol'], ['publishers.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_publisherschanges_changetime'), 'publisherschanges', ['changetime'], unique=False)
    op.create_index(op.f('ix_publisherschanges_changeuser'), 'publisherschanges', ['changeuser'], unique=False)
    op.create_index(op.f('ix_publisherschanges_srccol'), 'publisherschanges', ['srccol'], unique=False)


    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###

    op.drop_index(op.f('ix_publisherschanges_srccol'), table_name='publisherschanges')
    op.drop_index(op.f('ix_publisherschanges_changeuser'), table_name='publisherschanges')
    op.drop_index(op.f('ix_publisherschanges_changetime'), table_name='publisherschanges')
    op.drop_table('publisherschanges')
    op.drop_index(op.f('ix_publishers_changeuser'), table_name='publishers')
    op.drop_index(op.f('ix_publishers_changetime'), table_name='publishers')
    op.drop_table('publishers')
    ### end Alembic commands ###
