"""empty message

Revision ID: c3e717878823
Revises: fe6d24f28cd3
Create Date: 2016-05-15 20:27:22.542774

"""

# revision identifiers, used by Alembic.
revision = 'c3e717878823'
down_revision = 'fe6d24f28cd3'

from alembic import op
import sqlalchemy as sa
import citext
from sqlalchemy.dialects import postgresql

releaseshelper = sa.Table(
	'releases',
	sa.MetaData(),
	sa.Column('id',        sa.Integer, primary_key=True),
	sa.Column('volume',   sa.Float),
	sa.Column('chapter',  sa.Float),
	sa.Column('fragment', sa.Float),
)

releaseschangeshelper = sa.Table(
	'releaseschanges',
	sa.MetaData(),
	sa.Column('id',        sa.Integer, primary_key=True),
	sa.Column('volume',   sa.Float),
	sa.Column('chapter',  sa.Float),
	sa.Column('fragment', sa.Float),
)

releasetables = [releaseshelper, releaseschangeshelper]

def upgrade():
	### commands auto generated by Alembic - please adjust! ###
	op.add_column('covers', sa.Column('fragment', sa.Integer(), nullable=True))
	op.add_column('coverschanges', sa.Column('fragment', sa.Integer(), nullable=True))

	connection = op.get_bind()
	for tbl in releasetables:
		for row in connection.execute(tbl.select()):
			if row.chapter:
				frag = int(row.chapter * 100) % 100
				if frag:
					connection.execute(
						tbl.update().where(
							tbl.c.id == row.id
						).values(
							chapter  = int(row.chapter),
							fragment = frag
						)
					)

	op.alter_column('alternatenameschanges', 'name',
			   existing_type=sa.TEXT(),
			   type_=citext.CIText(),
			   existing_nullable=False)
	op.alter_column('covers', 'chapter',
			   existing_type=postgresql.DOUBLE_PRECISION(precision=53),
			   type_=sa.Integer(),
			   existing_nullable=True)
	op.alter_column('covers', 'volume',
			   existing_type=postgresql.DOUBLE_PRECISION(precision=53),
			   type_=sa.Integer(),
			   existing_nullable=True)
	op.alter_column('coverschanges', 'chapter',
			   existing_type=postgresql.DOUBLE_PRECISION(precision=53),
			   type_=sa.Integer(),
			   existing_nullable=True)
	op.alter_column('coverschanges', 'volume',
			   existing_type=postgresql.DOUBLE_PRECISION(precision=53),
			   type_=sa.Integer(),
			   existing_nullable=True)
	op.alter_column('releases', 'chapter',
			   existing_type=postgresql.DOUBLE_PRECISION(precision=53),
			   type_=sa.Integer(),
			   existing_nullable=True)
	op.alter_column('releases', 'fragment',
			   existing_type=postgresql.DOUBLE_PRECISION(precision=53),
			   type_=sa.Integer(),
			   existing_nullable=True)
	op.alter_column('releases', 'volume',
			   existing_type=postgresql.DOUBLE_PRECISION(precision=53),
			   type_=sa.Integer(),
			   existing_nullable=True)
	op.alter_column('releaseschanges', 'chapter',
			   existing_type=postgresql.DOUBLE_PRECISION(precision=53),
			   type_=sa.Integer(),
			   existing_nullable=True)
	op.alter_column('releaseschanges', 'fragment',
			   existing_type=postgresql.DOUBLE_PRECISION(precision=53),
			   type_=sa.Integer(),
			   existing_nullable=True)
	op.alter_column('releaseschanges', 'volume',
			   existing_type=postgresql.DOUBLE_PRECISION(precision=53),
			   type_=sa.Integer(),
			   existing_nullable=True)
	op.alter_column('translatorschanges', 'name',
			   existing_type=sa.TEXT(),
			   type_=citext.CIText(),
			   existing_nullable=False)



	### end Alembic commands ###


def downgrade():
	### commands auto generated by Alembic - please adjust! ###
	op.alter_column('translatorschanges', 'name',
			   existing_type=citext.CIText(),
			   type_=sa.TEXT(),
			   existing_nullable=False)
	op.alter_column('releaseschanges', 'volume',
			   existing_type=sa.Integer(),
			   type_=postgresql.DOUBLE_PRECISION(precision=53),
			   existing_nullable=True)
	op.alter_column('releaseschanges', 'fragment',
			   existing_type=sa.Integer(),
			   type_=postgresql.DOUBLE_PRECISION(precision=53),
			   existing_nullable=True)
	op.alter_column('releaseschanges', 'chapter',
			   existing_type=sa.Integer(),
			   type_=postgresql.DOUBLE_PRECISION(precision=53),
			   existing_nullable=True)
	op.alter_column('releases', 'volume',
			   existing_type=sa.Integer(),
			   type_=postgresql.DOUBLE_PRECISION(precision=53),
			   existing_nullable=True)
	op.alter_column('releases', 'fragment',
			   existing_type=sa.Integer(),
			   type_=postgresql.DOUBLE_PRECISION(precision=53),
			   existing_nullable=True)
	op.alter_column('releases', 'chapter',
			   existing_type=sa.Integer(),
			   type_=postgresql.DOUBLE_PRECISION(precision=53),
			   existing_nullable=True)
	op.alter_column('coverschanges', 'volume',
			   existing_type=sa.Integer(),
			   type_=postgresql.DOUBLE_PRECISION(precision=53),
			   existing_nullable=True)
	op.alter_column('coverschanges', 'chapter',
			   existing_type=sa.Integer(),
			   type_=postgresql.DOUBLE_PRECISION(precision=53),
			   existing_nullable=True)
	op.drop_column('coverschanges', 'fragment')
	op.alter_column('covers', 'volume',
			   existing_type=sa.Integer(),
			   type_=postgresql.DOUBLE_PRECISION(precision=53),
			   existing_nullable=True)
	op.alter_column('covers', 'chapter',
			   existing_type=sa.Integer(),
			   type_=postgresql.DOUBLE_PRECISION(precision=53),
			   existing_nullable=True)
	op.drop_column('covers', 'fragment')
	op.alter_column('alternatenameschanges', 'name',
			   existing_type=citext.CIText(),
			   type_=sa.TEXT(),
			   existing_nullable=False)
	### end Alembic commands ###

