"""empty message

Revision ID: c742f3c6e4ba
Revises: c3e717878823
Create Date: 2016-05-15 21:10:42.204434

"""

# revision identifiers, used by Alembic.
revision = 'c742f3c6e4ba'
down_revision = 'c3e717878823'

from alembic import op
import sqlalchemy as sa
import citext
from sqlalchemy.dialects import postgresql

watchesshelper = sa.Table(
	'watches',
	sa.MetaData(),
	sa.Column('id',        sa.Integer, primary_key=True),
	sa.Column('volume',   sa.Float),
	sa.Column('chapter',  sa.Float),
	sa.Column('fragment', sa.Float),
)


def upgrade():
	### commands auto generated by Alembic - please adjust! ###
	op.add_column('watches', sa.Column('fragment', sa.Integer(), nullable=True))

	connection = op.get_bind()
	for row in connection.execute(watchesshelper.select()):
		if row.chapter:
			frag = int(row.chapter * 100) % 100
			if frag:
				connection.execute(
					watchesshelper.update().where(
						watchesshelper.c.id == row.id
					).values(
						chapter  = int(row.chapter),
						fragment = frag
					)
				)

	op.alter_column('watches', 'chapter',
			   existing_type=postgresql.DOUBLE_PRECISION(precision=53),
			   type_=sa.Integer(),
			   existing_nullable=True)
	op.alter_column('watches', 'volume',
			   existing_type=postgresql.DOUBLE_PRECISION(precision=53),
			   type_=sa.Integer(),
			   existing_nullable=True)
	### end Alembic commands ###


def downgrade():
	### commands auto generated by Alembic - please adjust! ###
	op.alter_column('watches', 'volume',
			   existing_type=sa.Integer(),
			   type_=postgresql.DOUBLE_PRECISION(precision=53),
			   existing_nullable=True)
	op.alter_column('watches', 'chapter',
			   existing_type=sa.Integer(),
			   type_=postgresql.DOUBLE_PRECISION(precision=53),
			   existing_nullable=True)
	op.drop_column('watches', 'fragment')
	### end Alembic commands ###
