"""empty message

Revision ID: e5324ae0d804
Revises: d10a5fc828b8
Create Date: 2018-01-06 02:38:35.675123

"""

# revision identifiers, used by Alembic.
revision = 'e5324ae0d804'
down_revision = 'd10a5fc828b8'

from alembic import op
import sqlalchemy as sa
import citext


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('db_tag_entries',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('tag_str', citext.CIText(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('tag_str')
    )
    op.create_index(op.f('ix_db_tag_entries_tag_str'), 'db_tag_entries', ['tag_str'], unique=False)
    op.create_table('db_tags_link',
        sa.Column('series_id', sa.Integer(), nullable=False),
        sa.Column('link_weight', sa.Float(), nullable=False),
        sa.Column('tag_id', sa.Integer(), nullable=False),
        sa.Column('changeuser', sa.Integer(), nullable=True),
        sa.Column('changetime', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['changeuser'], ['users.id'], ),
        sa.ForeignKeyConstraint(['series_id'], ['series.id'], ),
        sa.ForeignKeyConstraint(['tag_id'], ['db_tag_entries.id'], ),
        sa.PrimaryKeyConstraint('series_id', 'tag_id'),
        sa.UniqueConstraint('series_id', 'tag_id')
    )
    op.create_index(op.f('ix_db_tags_link_changetime'), 'db_tags_link', ['changetime'], unique=False)
    op.create_index(op.f('ix_db_tags_link_changeuser'), 'db_tags_link', ['changeuser'], unique=False)
    op.create_table('db_tags_link_changes',
        sa.Column('srccol', sa.Integer(), nullable=False),
        sa.Column('series_id', sa.Integer(), nullable=False),
        sa.Column('link_weight', sa.Float(), nullable=False),
        sa.Column('tag_id', sa.Integer(), nullable=False),
        sa.Column('changeuser', sa.Integer(), nullable=False),
        sa.Column('changetime', sa.DateTime(), nullable=False),
        sa.Column('operation', sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(['changeuser'], ['users.id'], ),
        sa.ForeignKeyConstraint(['series_id'], ['series.id'], ),
        sa.ForeignKeyConstraint(['srccol'], ['series.id'], ondelete='SET NULL'),
        sa.ForeignKeyConstraint(['tag_id'], ['db_tag_entries.id'], ),
        sa.PrimaryKeyConstraint('series_id', 'tag_id', 'srccol', 'operation', 'changetime', 'changeuser')
    )
    op.create_index(op.f('ix_db_tags_link_changes_changetime'), 'db_tags_link_changes', ['changetime'], unique=False)
    op.create_index(op.f('ix_db_tags_link_changes_changeuser'), 'db_tags_link_changes', ['changeuser'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_db_tags_link_changes_changeuser'), table_name='db_tags_link_changes')
    op.drop_index(op.f('ix_db_tags_link_changes_changetime'), table_name='db_tags_link_changes')
    op.drop_table('db_tags_link_changes')
    op.drop_index(op.f('ix_db_tags_link_changeuser'), table_name='db_tags_link')
    op.drop_index(op.f('ix_db_tags_link_changetime'), table_name='db_tags_link')
    op.drop_table('db_tags_link')
    op.drop_index(op.f('ix_db_tag_entries_tag_str'), table_name='db_tag_entries')
    op.drop_table('db_tag_entries')
    # ### end Alembic commands ###
