"""empty message

Revision ID: ff1a89ef8c8c
Revises: 99efc33eaaa0
Create Date: 2017-08-01 21:58:28.916824

"""

# revision identifiers, used by Alembic.
revision = 'ff1a89ef8c8c'
down_revision = '99efc33eaaa0'

from alembic import op
import sqlalchemy as sa
import citext


def upgrade():
	### commands auto generated by Alembic - please adjust! ###

	# Unused old junk
	op.drop_column('serieschanges', 'volume')
	op.drop_column('serieschanges', 'chapter')
	op.drop_column('serieschanges', 'tot_volume')
	op.drop_column('serieschanges', 'tot_chapter')

	op.drop_column('series', 'volume')
	op.drop_column('series', 'chapter')
	op.drop_column('series', 'tot_volume')
	op.drop_column('series', 'tot_chapter')

	op.add_column('series', sa.Column('latest_chapter', sa.Float(), nullable=True))
	op.add_column('series', sa.Column('latest_fragment', sa.Float(), nullable=True))
	op.add_column('series', sa.Column('latest_published', sa.DateTime(), nullable=True))
	op.add_column('series', sa.Column('latest_volume', sa.Float(), nullable=True))

	op.add_column('serieschanges', sa.Column('latest_chapter', sa.Float(), nullable=True))
	op.add_column('serieschanges', sa.Column('latest_fragment', sa.Float(), nullable=True))
	op.add_column('serieschanges', sa.Column('latest_published', sa.DateTime(), nullable=True))
	op.add_column('serieschanges', sa.Column('latest_volume', sa.Float(), nullable=True))
	### end Alembic commands ###



def downgrade():
	### commands auto generated by Alembic - please adjust! ###
	op.drop_column('serieschanges', 'latest_volume')
	op.drop_column('serieschanges', 'latest_published')
	op.drop_column('serieschanges', 'latest_fragment')
	op.drop_column('serieschanges', 'latest_chapter')
	op.drop_column('series', 'latest_volume')
	op.drop_column('series', 'latest_published')
	op.drop_column('series', 'latest_fragment')
	op.drop_column('series', 'latest_chapter')
	### end Alembic commands ###
